// File mapping for documentation sections
const fileMapping = {
    'overview': 'overview.md',
    'duality-model': 'duality_model_architecture.md',
    'memory-system': 'memory_system_components.md',
    'voice-breath': 'voice_breath_systems.md',
    'truthfilter-joyoptimizer': 'truthfilter_joyoptimizer.md',
    'ritual-engine': 'ritual_engine_implementation.md',
    'prototype-specifications': 'prototype_specifications.md',
    'technical-architecture': 'technical_architecture.md',
    'ethical-framework': 'ethical_framework.md',
    'implementation-roadmap': 'implementation_roadmap.md',
    // Additional documentation files
    'user-guide': 'USER_GUIDE.md',
    'project-overview': 'project_overview.md',
    'project-blueprint': 'project_blueprint.md',
    'technical-implementation': 'technical_implementation.md',
    'technical-architecture-analysis': 'technical_architecture_analysis.md',
    'ethical-framework-analysis': 'ethical_framework_analysis.md',
    'ethical-framework-evaluation': 'ethical_framework_evaluation.md',
    'implementation-plan': 'implementation_plan.md',
    'implementation-roadmap-analysis': 'implementation_roadmap_analysis.md',
    'key-components': 'key_components_and_concepts.md',
    'relational-ai': 'relational_ai_concepts.md',
    'haptic-patterns': 'haptic_patterns.md',
    'user-interaction': 'user_interaction_features.md',
    'validation-report': 'validation_report.md',
    'use-case-overwhelm': 'uc_001_overwhelm.md',
    'improvement-plan': 'improvement_plan.md',
    'refinement-plan': 'refinement_plan.md',
    'final-report': 'final_report.md',
    'project-status': 'project_status_report.md',
    'advanced-enhancement': 'advanced_enhancement_analysis.md',
    'documentation-guide': 'documentation_guide.md',
    'documentation-index': 'documentation_index.md'
};
