name: Build and Deploy Documentation

on:
  push:
    branches: [ main, Rev04 ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: |
          npm install -g http-server
      
      - name: Create Directory Structure
        run: |
          mkdir -p docs/architecture
          mkdir -p docs/components
          mkdir -p docs/ethics
          mkdir -p docs/implementation
          mkdir -p docs/user_interaction
          mkdir -p docs/guides
          mkdir -p code/frontend
          mkdir -p code/backend
          mkdir -p code/core
          mkdir -p assets/images
          mkdir -p assets/sounds
          mkdir -p tests/unit
          mkdir -p tests/integration
          mkdir -p tests/e2e
          mkdir -p config/development
          mkdir -p config/production
      
      - name: Organize Documentation Files
        run: |
          # Move architecture docs
          mv *technical_architecture*.md docs/architecture/ 2>/dev/null || true
          mv *duality_model*.md docs/architecture/ 2>/dev/null || true

          # Move component docs
          mv *memory_system*.md docs/components/ 2>/dev/null || true
          mv *voice_breath*.md docs/components/ 2>/dev/null || true
          mv *ritual_engine*.md docs/components/ 2>/dev/null || true
          mv *truthfilter*.md docs/components/ 2>/dev/null || true

          # Move ethics docs
          mv *ethical_framework*.md docs/ethics/ 2>/dev/null || true

          # Move implementation docs
          mv *implementation*.md docs/implementation/ 2>/dev/null || true
          mv *roadmap*.md docs/implementation/ 2>/dev/null || true

          # Move user interaction docs
          mv *user_interaction*.md docs/user_interaction/ 2>/dev/null || true
          mv *haptic*.md docs/user_interaction/ 2>/dev/null || true
          mv *prototype*.md docs/user_interaction/ 2>/dev/null || true

          # Move guide docs
          mv USER_GUIDE.md docs/guides/ 2>/dev/null || true
          mv *documentation_guide*.md docs/guides/ 2>/dev/null || true

          # Move web files
          mv *.html code/frontend/ 2>/dev/null || true
          mv *.js code/frontend/ 2>/dev/null || true
          
          # Move images to assets
          mv *.webp assets/images/ 2>/dev/null || true
          mv *.png assets/images/ 2>/dev/null || true
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
